apply plugin: "java"

version '1.0'

sourceCompatibility = JavaVersion.VERSION_16

sourceSets.main.java.srcDirs = ["src"]

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

repositories{
    mavenCentral()
    maven { url "https://raw.githubusercontent.com/Anuken/Mindustry/master/repository" }
    ivy {
        url 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/download/[revision]/server-release.jar'}
        metadataSources{ artifact() }
    }

    ivy {
        url 'https://github.com/'
        patternLayout{artifact '/[organisation]/[module]/releases/download/[revision]/jabel.jar'}
        metadataSources{ artifact() }
    }
}

ext{
    //the build number that this plugin is made for
    mindustryVersion = 'v158.1'
}

//java 8 backwards compatibility flag
allprojects{
    tasks.withType(JavaCompile){
        options.compilerArgs.addAll(['--release', '8', '-Xlint:deprecation'])
    }
}

dependencies{
    //discord deps
    def jdaVersion = '6.4.2'
    def webhooksVersion = '0.8.4'

    compileOnly "Anuken:Mindustry:$mindustryVersion"
    annotationProcessor "Anuken:jabel:v1.0.0"
    //change 'implementation' to 'compile' in old Gradle versions
    implementation("net.dv8tion:JDA:$jdaVersion") {
        exclude module: 'opus-java'
    }
    implementation "club.minnced:discord-webhooks:$webhooksVersion"
}

jar{
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE) //fix weird error about META-INF/LICENSE being a duplicate
    archiveFileName = "${project.archivesBaseName}.jar"
    from{
        configurations.runtimeClasspath.collect{it.isDirectory() ? it : zipTree(it)}
    }

    from(rootDir){
        include "plugin.json"
    }
}
